{% set name = "unearth" %}
{% set version = "0.17.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unearth-{{ version }}.tar.gz
  sha256: a19e1c02e64b40518d088079c7416fc41b45a648b81a4128aac02597234ee6ba

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - unearth = unearth.__main__:cli
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pdm-backend
    - setuptools
  run:
    - cached-property >=1.5.2
    - packaging >=20
    - python >={{ python_min }}
    - requests >=2.25
    - httpx

test:
  imports:
    - unearth
  source_files:
    - tests
  commands:
    - pytest tests
  requires:
    - pip
    - pytest >=6.1
    - pytest-mock
    - pytest-httpserver >=1.0.4
    - flask >=2.1.2
    - requests-wsgi-adapter >=0.4.1
    - trustme >=0.9.0
    - keyring
    - openssl <3.0.0
    - python {{ python_min }}

about:
  home: https://pypi.org/project/unearth/
  summary: A utility to fetch and download python packages
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - theAeon
