{% set name = "unearth" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unearth-{{ version }}.tar.gz
  sha256: 69b9d4d86173f6fbe8cf685c829c31a60d0c82e1bcd6c5b59af8fd564bf0dc1a

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - unearth = unearth.__main__:cli
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - pdm-backend
    - setuptools
  run:
    - cached-property >=1.5.2
    - packaging >=20
    - python >=3.7
    - requests >=2.25

test:
  imports:
    - unearth
  source_files:
    - tests
  commands:
    - pytest tests
  requires:
    - pip
    - pytest >=6.1
    - pytest-httpserver >=1.0.4
    - flask >=2.1.2
    - requests-wsgi-adapter >=0.4.1
    - trustme >=0.9.0
    - keyring
    - openssl <3.0.0

about:
  home: https://pypi.org/project/unearth/
  summary: A utility to fetch and download python packages
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - theAeon
